const swaggerAutogen = require('swagger-autogen')()
const doc = {
    info: {
        version: "1.0.0",
        title: "Exam project",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    definitions: {
        Register: {
            $firstName: "John",
            $lastName: "Doe",
            $username: "johndoe",
            $email: "johndoe@example.com",
            $password: "password",
            $address: "Exampleville 22",
            $telephoneNumber: "52414144"
            },
            Login: {
                $username: "johndoe",
                $password: "password"
            },
            Brand: {
                $name: "Sony Ericsson"
            },
            UpdateBrand: {
                $name: "Sony Mobile Communications"
            },
            Category: {
                $name: "Gaming Consoles"
            },
            UpdateCategory: {
                $name: "Gaming Systems"
            },
            Product: {
                $name: "Playstation 5",
                $description: "Sony's latest gaming console",
                $price: 699,
                $quantity: 10,
                $discount: 0,
                $categoryId: 1,
                $brandId: 1,
                $isDeleted: false,
                $imgURL: "https://gmedia.playstation.com/is/image/SIEPDC/ps5-product-thumbnail-01-en-14sep21"
            },
            UpdateProduct: {
                $name: "Playstation 6",
                $description: "Sony's futuristic gaming console",
                $price: 8000,
                $quantity: 0,
                $discount: 0,
                $categoryId: 1,
                $brandId: 1,
                $isDeleted: false,
                $imgURL: "https://i.ytimg.com/vi/QNwJdTqZvts/maxresdefault.jpg"
            },
            Membership: {
                $statusName: "Platinum",
                $discount: 50
            },
            UpdateMembership: {
                $statusName: "Diamond",
                $discount: 50
            },
            Search: {
                $productName: "iPhone",
                $categoryName: "Phones",
                $brandName: "Apple"
            },
            Cart: {
                $productId: 1,
                $quantity: 1
            },
            UpdateCart: {
                $productId: 1,
                $quantity: 2
            },
            Order: {
                $status: "Ordered",
            }
        },
    securityDefinitions: {
        Bearer: {
          type: "apiKey",
          name: "Authorization",
          in: "header",
          description: "Token should manually have been added as a cookie by default but if that does not work the JWT token can be added here with the prefix: Bearer followed by the token"
        }
      }
    }

const outputFile = './swagger-output.json'
const endpointsFiles = ['./app.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./bin/www')
})